Have error messages actually go to stderr

diff --git a/shell/git_reclone b/shell/git_reclone
--- a/shell/git_reclone
+++ b/shell/git_reclone
@@ -46,7 +46,7 @@ _EOF_
 fi
 
 if [ -z "$(command -v git)" ]; then
-	echo "${PROGRAM_NAME}: git cannot be found in the PATH!"
+	echo "${PROGRAM_NAME}: git cannot be found in the PATH!" >&2
 	exit 1
 fi
 
@@ -54,7 +54,7 @@ while [ $# -gt 0 ]; do
     git_repo_dir="$1"
     cd "${git_repo_dir}"
     if ! git rev-parse --quiet --is-inside-work-tree > /dev/null 2>&1; then
-        echo -e "${PROGRAM_NAME}: ${git_repo_dir} is not a git repo!"
+        echo -e "${PROGRAM_NAME}: ${git_repo_dir} is not a git repo!" >&2
         cd - > /dev/null
         exit
     fi
