Add disable-github-actions.py
Should also add that this script is now integrated
into update-remote-forks. As I am tired of seeing emails
about workflows failing.

diff --git a/update-remote-forks b/update-remote-forks
--- a/update-remote-forks
+++ b/update-remote-forks
@@ -24,7 +24,8 @@ esac
 PROGRAM_NAME="$(basename "$0")"
 PYTHON_EXECUTABLE="$(which python3)"
 TEMP_DIR_NAME="$PROGRAM_NAME-temp"
-FORKED_GIT_REMOTE_NAME="custom_fork"
+DISABLE_GITHUB_ACTIONS_SCRIPTNAME="disable-github-actions.py"
+FORKED_GIT_REMOTE_NAME="custom-fork"
 WEBHOSTED_GIT_ACCOUNT_URL="https://github.com/reap2sow1/"
 declare -A FORKED_REPO_NAMES_TO_UPSTREAM_URLS=(
     # ["forked_repo_name"]=>"upstream_url"
@@ -35,9 +36,14 @@ if [ -z "$(which git)" ]; then
     exit 1
 fi
 
+if [ -z "$(which $DISABLE_GITHUB_ACTIONS_SCRIPTNAME)" ]; then
+    echo "${PROGRAM_NAME}: $DISABLE_GITHUB_ACTIONS_SCRIPTNAME cannot be found on the PATH!"
+    exit 1
+fi
+
 if [ -z "$PYTHON_EXECUTABLE" ] || [ "$($PYTHON_EXECUTABLE --version | grep --regexp "Python 3\..*" --count)" -eq 0 ]; then
-        echo "${PROGRAM_NAME}: 'python3' does not point to a python 3 interpreter"
-        exit 1
+    echo "${PROGRAM_NAME}: 'python3' does not point to a python 3 interpreter"
+    exit 1
 fi
 
 if [ -d "$TEMP_DIR_NAME" ]; then
@@ -47,8 +53,8 @@ fi
 mkdir "$TEMP_DIR_NAME" || exit 1
 cd "$TEMP_DIR_NAME" || exit 1
 
-for forked_repo in "${!FORKED_REPO_NAMES_TO_UPSTREAM_URLS[@]}"; do
-    upstream="${FORKED_REPO_NAMES_TO_UPSTREAM_URLS["$forked_repo"]}"
+for forked_repo_name in "${!FORKED_REPO_NAMES_TO_UPSTREAM_URLS[@]}"; do
+    upstream="${FORKED_REPO_NAMES_TO_UPSTREAM_URLS["$forked_repo_name"]}"
     # NOTE: "$upstream" should follow parameter expansion, then being 
     # seen to python as os.path.basename("{results from parameter expansion}")
     upstream_repo_name="$($PYTHON_EXECUTABLE -c 'import os; print(os.path.basename('\""$upstream"\"'))')"
@@ -57,12 +63,13 @@ for forked_repo in "${!FORKED_REPO_NAMES_TO_UPSTREAM_URLS[@]}"; do
     # seqeuence of commands inspired from:
     # https://stackoverflow.com/questions/15779740/how-to-update-my-fork-to-have-the-same-branches-and-tags-as-the-original-reposit
     # https://stackoverflow.com/questions/379081/track-all-remote-git-branches-as-local-branches/6300386#answer-27234826
-    git remote add "$FORKED_GIT_REMOTE_NAME" "$($PYTHON_EXECUTABLE -c 'import os; print(os.path.join('\""$WEBHOSTED_GIT_ACCOUNT_URL"\"', '\""$forked_repo"\"'))')"
+    git remote add "$FORKED_GIT_REMOTE_NAME" "$($PYTHON_EXECUTABLE -c 'import os; print(os.path.join('\""$WEBHOSTED_GIT_ACCOUNT_URL"\"', '\""$forked_repo_name"\"'))')"
     for short_refname in $(git branch --remotes | grep --invert-match --extended-regexp "HEAD|master"); do 
         "${GIT_BRANCH[@]}" --track "${short_refname#*/}" "$short_refname"; 
     done
     "${GIT_PUSH[@]}" --all "$FORKED_GIT_REMOTE_NAME"
     "${GIT_PUSH[@]}" --tags "$FORKED_GIT_REMOTE_NAME"
+    "$PYTHON_EXECUTABLE" "${DISABLE_GITHUB_ACTIONS_SCRIPTNAME}" "$forked_repo_name"
     cd ..
 done
 
